Last login: Wed Sep 27 15:49:43 on ttys000
by@MBP-von-Philip ~ % sudo apachectl start

Password:
httpd (pid 688) already running
by@MBP-von-Philip ~ % sudo nano /usr/local/etc/httpd/other/myflaskapp.conf


































































  UW PICO 5.09                          File: /usr/local/etc/httpd/other/myflaskapp.conf                           Modified  

<VirtualHost *:80>
    ServerName monalexdictioanry.com
    ServerAdmin psv25032005@gmail.com          

    WSGIDaemonProcess myflaskapp user=user group=staff threads=5
    WSGIScriptAlias / /User/by/Documents/Github/monalex/dictionary_project/wsgi.py

    <Directory /User/by/Documents/Github/monalex/dictionary_project/>       
        WSGIProcessGroup myflaskapp
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>

    ErrorLog "/User/by/Documents/Github/monalex/dictionary_project/error.log"
    CustomLog "/User/by/Documents/Github/monalex/dictionary_project/access.log" combined
</VirtualHost>


















































                                                                                                                             
^G Get Help         ^O WriteOut         ^R Read File        ^Y Prev Pg          ^K Cut Text         ^C Cur Pos          
^X Exit             ^J Justify          ^W Where is         ^V Next Pg          ^U UnCut Text       ^T To Spell         
